version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - APP_NAME=${APP_NAME}
      - APP_ENV=${APP_ENV}
      - LOG_LEVEL=${LOG_LEVEL}


